version: '3.1'

services:

  db:
    image: postgres:11.2-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 9090:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=brunshzl@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=adminadmin
    volumes:
      - ./pgbkp:/var/lib/pgadmin/storage/
